import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Que de la qualité ici',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
